"""add_oauth_fields_to_user

Revision ID: 0daee9bb5b1d
Revises: 
Create Date: 2026-01-22 23:22:09.442750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0daee9bb5b1d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('progress_percent', sa.Float(), nullable=True))
    op.add_column('user_progress', sa.Column('exercises_completed', sa.Integer(), nullable=True))
    op.add_column('user_progress', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_progress', sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_user_progress_lesson_id'), 'user_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_unique_constraint('unique_user_lesson', 'user_progress', ['user_id', 'lesson_id'])
    op.drop_constraint('user_progress_lesson_id_fkey', 'user_progress', type_='foreignkey')
    op.drop_constraint('user_progress_user_id_fkey', 'user_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_progress', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.create_foreign_key('user_progress_user_id_fkey', 'user_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_progress_lesson_id_fkey', 'user_progress', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint('unique_user_lesson', 'user_progress', type_='unique')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_lesson_id'), table_name='user_progress')
    op.drop_column('user_progress', 'last_accessed_at')
    op.drop_column('user_progress', 'started_at')
    op.drop_column('user_progress', 'exercises_completed')
    op.drop_column('user_progress', 'progress_percent')
    # ### end Alembic commands ###
